[pytest]
addopts = -v 
    --cov=./ 
    --cov-report=html 
    --cov-report=xml 
    --cov-fail-under=90 
    --benchmark-max-time=5 
    --benchmark-columns=mean,median,stddev,rounds,iterations
markers =
    integration: marks tests as integration tests
    performance: marks tests as performance benchmark tests
    security: marks tests as security validation tests
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
EOL < /dev/null
